### ISSUE TITLE
Connection unstable 

### ISSUE THREAD

**Issue by marcel-bluestone** [ShellAddicted/BNO055ESP32#6]
Hello,

@ShellAddicted: the examples work sometimes, most of the time I receive the following error:

uart: ALREADY NULL
E (1088) BNO055ESP32Example: Setup Failed, Error: timeout expired, if you see this often, try to increase timeoutMS.

The wiring should be ok, I increased the timeout MS from 30 to 50, 100 and even 1000 with the same result.
It seems, that only once the esp and bno055 had been disconnected from USB for several minutes, there is a chance that everything works as it should. 
I experience the same behaviour with various BNO055s. 
Is there a way to get this more stable by tweaking the config here and there, or is it known there is a degree of uncertainty whether the sensor will deliver values after booting the Esp-chip?

**Comment by ShellAddicted** [comment]
Hi, the only advice I have is to check your wiring, making sure that the wires are as short as possible, make a good  (shaking proof) connection with the IMU PCB, and both your boards have compatible logic levels.

I've never experienced interference caused by an USB connection, so I can't help you about that.
But I've got definitely usable results, for hobby-grade stuff obviously, on a rc car.

If you discover that your problem is a bug in this component, feel free to reopen this with more details.
